// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	CreateCoach(ctx context.Context, arg CreateCoachParams) (Coach, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateTeam(ctx context.Context, coachID int64) (Team, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteCoach(ctx context.Context, username string) error
	DeletePlayer(ctx context.Context, id int64) error
	DeleteTeam(ctx context.Context, id int64) error
	GetCoachById(ctx context.Context, id int64) (Coach, error)
	GetCoachByUsername(ctx context.Context, username string) (Coach, error)
	GetPlayer(ctx context.Context, id int64) (Player, error)
	GetPlayerForUpdate(ctx context.Context, id int64) (Player, error)
	GetPlayers(ctx context.Context, arg GetPlayersParams) ([]Player, error)
	GetTeam(ctx context.Context, id int64) (Team, error)
	GetTeamByCoach(ctx context.Context, coachID int64) (Team, error)
	GetTeamsPlayers(ctx context.Context, arg GetTeamsPlayersParams) ([]Player, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	IncreaseWinTeam(ctx context.Context, arg IncreaseWinTeamParams) (Team, error)
	ListTeams(ctx context.Context, arg ListTeamsParams) ([]Team, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	UpdateCoachPassword(ctx context.Context, arg UpdateCoachPasswordParams) (Coach, error)
	UpdatePlayersTeam(ctx context.Context, arg UpdatePlayersTeamParams) (Player, error)
	UpdateTeamsWin(ctx context.Context, arg UpdateTeamsWinParams) (Team, error)
}

var _ Querier = (*Queries)(nil)
