// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: transfers.sql

package db

import (
	"context"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
  player,
  from_team,
  to_team
) VALUES (
  $1, $2, $3
) RETURNING id, player, from_team, to_team
`

type CreateTransferParams struct {
	Player   int64 `json:"player"`
	FromTeam int64 `json:"from_team"`
	ToTeam   int64 `json:"to_team"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer, arg.Player, arg.FromTeam, arg.ToTeam)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Player,
		&i.FromTeam,
		&i.ToTeam,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, player, from_team, to_team FROM transfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.Player,
		&i.FromTeam,
		&i.ToTeam,
	)
	return i, err
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, player, from_team, to_team FROM transfers
WHERE 
    from_team = $1 OR
    to_team = $2
ORDER BY id
LIMIT $3
OFFSET $4
`

type ListTransfersParams struct {
	FromTeam int64 `json:"from_team"`
	ToTeam   int64 `json:"to_team"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers,
		arg.FromTeam,
		arg.ToTeam,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.Player,
			&i.FromTeam,
			&i.ToTeam,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
